name: CI


on:
  pull_request:
  push:
    branches:
      - '*'
  schedule:
    # daily (`@daily` not supported, see
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events )
    #
    # Runs on default/base branch (see
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule )
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # see https://github.com/goanpeca/setup-miniconda/#important
        shell: bash -l {0}

    steps:
      # CI setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conda Bootstrap
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          channel-priority: strict
          channels: conda-forge
          python-version: 3.9
      - name: Conda Config
        run: |
          conda config --set always_yes yes
          conda config --set changeps1 no
          conda config --set pip_interop_enabled True

      # Installation into the `test` environment

#      - name: Conda Install conda-requirements.txt
#        # run this AFTER pyarrow, since this is less restrictive (so conda doesn't spend too much time downgrading)
#        run: conda install --file=conda-requirements.txt
      - name: Pip Install
        run: pip install .

      - name: Run test
        run: pytest test_bot.py

      - name: Run Bot and Post Score to Leaderboard
        run: |
          score=$(python bot.py && grep 'Total cost is: EUR' && grep -Eo '[0-9]{1,4}.[0-9]{1,4}')
          echo $score
          # curl -i --header 'Content-Type: application/json' \
          #      --request POST --data '{\"user\":\"dummy-player\",\"score\":$score}' \
          #      -u $LEADERBOARD_API_USERNAME:$LEADERBOARD_API_PASSWORD \
          #      $LEADERBOARD_API_ENDPOINT
        env:
          LEADERBOARD_API_USERNAME: pydata-leaderboatd-api-user
          LEADERBOARD_API_PASSWORD: svjYxP6P3Tpnp4meK32N4ZwN22H8ddD5xg4hXrhf
          LEADERBOARD_API_ENDPOINT: https://leaderboard-server.pydata-bot-tournament.eu.live.external.byp.ai/add-user-score


